import { CheckCircle2, CircleAlert, LoaderCircle, Network, Plus, Puzzle, Save, Search, ShieldCheck, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { AgentMCPServerSetting, AgentSettings, AgentSkillSetting, BackendConfig, SecretSettingStatus } from '../lib/backend';
import { requestJSON } from '../lib/backend';

type Props = { config: BackendConfig | null; open: boolean };
type SecretDraft = { id: string; key: string; value: string; configured: boolean; masked?: string; remove: boolean };
type ServerDraft = Omit<AgentMCPServerSetting, 'args' | 'env' | 'headers'> & { id: string; originalName: string; argsText: string; env: SecretDraft[]; headers: SecretDraft[] };
let sequence = 0;
const id = (prefix: string) => `${prefix}-${Date.now()}-${++sequence}`;

export function AgentCapabilitiesPanel({ config, open }: Props) {
	const [skills, setSkills] = useState<AgentSkillSetting[]>([]);
	const [servers, setServers] = useState<ServerDraft[]>([]);
	const [search, setSearch] = useState('');
	const [state, setState] = useState<'idle' | 'loading' | 'saving' | 'saved' | 'error'>('idle');
	const [message, setMessage] = useState('');
	useEffect(() => {
		if (!open || !config) return;
		let cancelled = false; setState('loading');
		requestJSON<{ data: AgentSettings }>(config, '/api/v1/settings/agent').then(({ data }) => { if (!cancelled) { setSkills(data.skills || []); setServers((data.mcp_servers || []).map(toDraft)); setState('idle'); } }).catch((error) => { if (!cancelled) { setState('error'); setMessage(error instanceof Error ? error.message : '讀取 AI 能力設定失敗'); } });
		return () => { cancelled = true; };
	}, [config, open]);
	const shown = useMemo(() => { const query = search.trim().toLowerCase(); return query ? skills.filter((item) => `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(query)) : skills; }, [skills, search]);
	const save = async () => { if (!config) return; setState('saving'); try { const response = await requestJSON<{ data: AgentSettings }>(config, '/api/v1/settings/agent', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ skills: skills.map(({ name, enabled }) => ({ name, enabled })), mcp_servers: servers.map(toUpdate) }) }); setSkills(response.data.skills || []); setServers((response.data.mcp_servers || []).map(toDraft)); setState('saved'); setMessage('Skill 與 MCP 設定已儲存；secret 不會回傳至頁面。'); } catch (error) { setState('error'); setMessage(error instanceof Error ? error.message : '儲存 AI 能力設定失敗'); } };
	const updateServer = (serverID: string, patch: Partial<ServerDraft>) => setServers((items) => items.map((item) => item.id === serverID ? { ...item, ...patch } : item));
	return <section className="settings-section agent-capabilities" onKeyDown={(event) => { if (event.key === 'Enter' && event.target instanceof HTMLInputElement) event.preventDefault(); }}>
		<div className="settings-section-title"><Puzzle size={18} /><div><h3>Skill 與 MCP</h3><p>一般 AI 對話可使用的本機能力；台股 AI Research 不會繼承這些設定。</p></div></div>
		{state === 'loading' ? <div className="agent-settings-loading"><LoaderCircle className="spin" size={18} />讀取 AI 能力設定</div> : <><div className="agent-settings-block"><div className="agent-settings-heading"><div><strong>Skills</strong><span>{skills.filter((item) => item.enabled).length}/{skills.length} 個已啟用</span></div><label><Search size={14} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜尋 Skill" /></label></div><div className="skill-settings-list">{shown.map((skill) => <label className="skill-setting-item" key={skill.name}><span><strong>{skill.name}</strong><small>{skill.category} · {skill.description || '暫無描述'}</small></span><input type="checkbox" checked={skill.enabled} onChange={(event) => setSkills((items) => items.map((item) => item.name === skill.name ? { ...item, enabled: event.target.checked } : item))} /></label>)}{!shown.length && <div className="agent-settings-empty">沒有符合的本機 Skill</div>}</div></div>
		<div className="agent-settings-block"><div className="agent-settings-heading"><div><strong>MCP Servers</strong><span>{servers.filter((item) => item.enabled).length}/{servers.length} 個已啟用</span></div><button type="button" onClick={() => setServers((items) => [...items, emptyServer()])}><Plus size={14} />新增 MCP</button></div><div className="mcp-server-list">{servers.map((server) => <ServerCard key={server.id} server={server} onChange={(patch) => updateServer(server.id, patch)} onRemove={() => setServers((items) => items.filter((item) => item.id !== server.id))} />)}{!servers.length && <div className="agent-settings-empty"><Network size={20} /><strong>尚未設定 MCP Server</strong><span>可加入明確設定的 stdio、HTTP 或 SSE 服務。</span></div>}</div></div></>}
		<div className={`agent-settings-footer ${state}`}><span>{state === 'saved' ? <CheckCircle2 size={14} /> : state === 'error' ? <CircleAlert size={14} /> : <ShieldCheck size={14} />}{message || 'MCP 環境變數與標頭以 secret 處理，頁面只顯示遮罩狀態。'}</span><button type="button" onClick={() => void save()} disabled={!config || state === 'loading' || state === 'saving'}>{state === 'saving' ? <LoaderCircle className="spin" size={15} /> : <Save size={15} />}儲存 Skill/MCP</button></div>
	</section>;
}

function ServerCard({ server, onChange, onRemove }: { server: ServerDraft; onChange: (patch: Partial<ServerDraft>) => void; onRemove: () => void }) { return <article className={`mcp-server-card ${server.enabled ? '' : 'disabled'}`}><header><label><input type="checkbox" checked={server.enabled} onChange={(event) => onChange({ enabled: event.target.checked })} /><span>{server.enabled ? '啟用' : '停用'}</span></label><button type="button" onClick={onRemove} aria-label="刪除 MCP Server"><Trash2 size={14} /></button></header><div className="settings-grid two-columns"><label><span>名稱</span><input value={server.name} onChange={(event) => onChange({ name: event.target.value })} /></label><label><span>傳輸方式</span><select value={server.transport} onChange={(event) => onChange({ transport: event.target.value as ServerDraft['transport'] })}><option value="stdio">本機命令（stdio）</option><option value="http">Streamable HTTP</option><option value="sse">SSE</option></select></label></div>{server.transport === 'stdio' ? <><label><span>啟動命令</span><input value={server.command || ''} onChange={(event) => onChange({ command: event.target.value })} /></label><label><span>參數（每行一個）</span><textarea value={server.argsText} onChange={(event) => onChange({ argsText: event.target.value })} /></label></> : <label><span>服務 URL</span><input value={server.url || ''} onChange={(event) => onChange({ url: event.target.value })} placeholder="https://example.com/mcp" /></label>}<SecretFields title="環境變數" values={server.env} onChange={(env) => onChange({ env })} /><SecretFields title="HTTP 標頭" values={server.headers} onChange={(headers) => onChange({ headers })} /><div className="settings-grid two-columns"><label><span>呼叫逾時（秒）</span><input type="number" min="0" max="3600" value={server.timeout || 0} onChange={(event) => onChange({ timeout: Number(event.target.value) })} /></label><label><span>連線逾時（秒）</span><input type="number" min="0" max="600" value={server.connect_timeout || 0} onChange={(event) => onChange({ connect_timeout: Number(event.target.value) })} /></label></div><label className="mcp-parallel-toggle"><span><strong>允許並行工具呼叫</strong><small>只在確認服務可安全並行時開啟。</small></span><input type="checkbox" checked={Boolean(server.supports_parallel_tool_calls)} onChange={(event) => onChange({ supports_parallel_tool_calls: event.target.checked })} /></label></article>; }
function SecretFields({ title, values, onChange }: { title: string; values: SecretDraft[]; onChange: (values: SecretDraft[]) => void }) { const update = (idValue: string, patch: Partial<SecretDraft>) => onChange(values.map((item) => item.id === idValue ? { ...item, ...patch } : item)); return <fieldset className="mcp-secret-fields"><legend>{title}</legend>{values.map((item) => <div key={item.id} className="settings-grid two-columns"><input value={item.key} placeholder="名稱" onChange={(event) => update(item.id, { key: event.target.value })} /><input type="password" value={item.value} placeholder={item.configured ? `${item.masked || '已設定'}；留白即保留` : '輸入 secret'} onChange={(event) => update(item.id, { value: event.target.value })} /><label><input type="checkbox" checked={item.remove} onChange={(event) => update(item.id, { remove: event.target.checked })} />清除</label><button type="button" onClick={() => onChange(values.filter((entry) => entry.id !== item.id))}>移除欄位</button></div>)}<button type="button" onClick={() => onChange([...values, { id: id('secret'), key: '', value: '', configured: false, remove: false }])}><Plus size={13} />新增 {title}</button></fieldset>; }
function emptyServer(): ServerDraft { return { id: id('mcp'), name: '', originalName: '', enabled: true, transport: 'stdio', command: '', argsText: '', env: [], url: '', headers: [], timeout: 300, connect_timeout: 60, supports_parallel_tool_calls: false }; }
function toDraft(server: AgentMCPServerSetting): ServerDraft { return { ...server, id: id('mcp'), originalName: server.name, transport: server.transport || 'stdio', argsText: (server.args || []).join('\n'), env: secretDrafts(server.env, 'env'), headers: secretDrafts(server.headers, 'header') }; }
function secretDrafts(values: Record<string, SecretSettingStatus> | undefined, prefix: string): SecretDraft[] { return Object.entries(values || {}).map(([key, value]) => ({ id: id(prefix), key, value: '', configured: value.configured, masked: value.masked, remove: false })); }
function toUpdate(server: ServerDraft) { const serialize = (items: SecretDraft[]) => ({ values: Object.fromEntries(items.filter((item) => item.key.trim() && item.value.trim()).map((item) => [item.key.trim(), item.value.trim()])), clear: items.filter((item) => item.key.trim() && item.remove).map((item) => item.key.trim()) }); const env = serialize(server.env); const headers = serialize(server.headers); return { name: server.name.trim(), original_name: server.originalName, enabled: server.enabled, transport: server.transport, command: (server.command || '').trim(), args: server.argsText.split(/\r?\n/).map((value) => value.trim()).filter(Boolean), env: env.values, clear_env: env.clear, url: (server.url || '').trim(), headers: headers.values, clear_headers: headers.clear, timeout: server.timeout || 0, connect_timeout: server.connect_timeout || 0, supports_parallel_tool_calls: Boolean(server.supports_parallel_tool_calls) }; }
