import { Bot, MessageSquarePlus, Send, Settings, Square, Trash2, UserRound } from 'lucide-react';
import { FormEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { type AppSettings, type BackendConfig, requestJSON } from '../lib/backend';
import { streamAgentPrompt } from '../lib/agent-stream';
import { ChatConversation, ChatMessage, createChatConversation, createChatID, deriveChatTitle, parseStoredConversations, storeableConversations } from '../lib/chat';
import { MessageContent } from './MarkdownContent';

type Props = { config: BackendConfig | null; refreshKey: number; initialPrompt?: string; onInitialPromptConsumed?: () => void; onOpenSettings: () => void };
type RuntimeState = 'loading' | 'ready' | 'unconfigured' | 'unavailable';
type RequestState = 'idle' | 'streaming' | 'error';
const storageKey = 'easy-stock.ai-conversations.v1';
const legacyStorageKey = 'a-stock-ai.ai-conversations.v1';

function readConversations(): ChatConversation[] { try { const current=localStorage.getItem(storageKey); const parsed=parseStoredConversations(current ?? localStorage.getItem(legacyStorageKey)); if (current===null&&parsed.length) localStorage.setItem(storageKey,JSON.stringify(storeableConversations(parsed))); return parsed } catch { return [] } }
function now() { return new Date().toISOString() }

export function AIChatWorkspace({ config, refreshKey, initialPrompt, onInitialPromptConsumed, onOpenSettings }: Props) {
	const [conversations,setConversations]=useState<ChatConversation[]>(readConversations);
	const [activeID,setActiveID]=useState(() => conversations[0]?.id ?? '');
	const [draft,setDraft]=useState(''); const [runtime,setRuntime]=useState<RuntimeState>('loading'); const [request,setRequest]=useState<RequestState>('idle');
	const [notice,setNotice]=useState(''); const [pendingID,setPendingID]=useState('');
	const abortRef=useRef<AbortController|null>(null); const requestRef=useRef(0); const endRef=useRef<HTMLDivElement|null>(null); const inputRef=useRef<HTMLTextAreaElement|null>(null);
	const active=useMemo(()=>conversations.find(item=>item.id===activeID)??null,[conversations,activeID]);
	const replaceConversation=(next:ChatConversation)=>setConversations(items=>[next,...items.filter(item=>item.id!==next.id)]);
	useEffect(()=>{ try{localStorage.setItem(storageKey,JSON.stringify(storeableConversations(conversations)))}catch{} },[conversations]);
	useEffect(()=>{ endRef.current?.scrollIntoView({block:'end',behavior:'smooth'}) },[active?.messages.length,request]);
	useEffect(()=>{ const prompt=initialPrompt?.trim(); if(prompt){setDraft(prompt); inputRef.current?.focus(); onInitialPromptConsumed?.()} },[initialPrompt,onInitialPromptConsumed]);
	useEffect(()=>()=>abortRef.current?.abort(),[]);
	useEffect(()=>{ if(!config){setRuntime('unavailable');return} let cancelled=false; setRuntime('loading'); requestJSON<{data:AppSettings}>(config,'/api/v1/settings').then(({data})=>{if(cancelled)return; const status=data.agent??data.hermes; setRuntime(!status.available?'unavailable':status.configured?'ready':'unconfigured')}).catch(()=>!cancelled&&setRuntime('unavailable')); return()=>{cancelled=true} },[config,refreshKey]);
	const createConversation=()=>{ abortRef.current?.abort(); requestRef.current++; const conversation=createChatConversation(); replaceConversation(conversation); setActiveID(conversation.id); setDraft(''); setRequest('idle'); setPendingID(''); setNotice(''); inputRef.current?.focus() };
	const removeConversation=(id:string)=>{if(id===activeID) abortRef.current?.abort(); setConversations(items=>{const next=items.filter(item=>item.id!==id); if(id===activeID)setActiveID(next[0]?.id??''); return next})};
	const stop=()=>abortRef.current?.abort();
	const submit=async(event?:FormEvent)=>{event?.preventDefault(); const prompt=draft.trim(); if(!prompt||!config||runtime!=='ready'||request==='streaming')return; const conversation=active??createChatConversation(); const started=now(); const user:ChatMessage={id:createChatID('message'),role:'user',content:prompt,created_at:started}; const assistant:ChatMessage={id:createChatID('message'),role:'assistant',content:'',created_at:started}; const pending={...conversation,title:conversation.messages.length?conversation.title:deriveChatTitle(prompt),messages:[...conversation.messages,user,assistant],updated_at:started}; replaceConversation(pending); setActiveID(pending.id); setDraft(''); setPendingID(assistant.id); setRequest('streaming'); setNotice(''); const generation=++requestRef.current; const controller=new AbortController(); abortRef.current=controller;
		const update=(fn:(item:ChatConversation)=>ChatConversation)=>setConversations(items=>items.map(item=>item.id===pending.id&&generation===requestRef.current?fn(item):item));
		try { const result=await streamAgentPrompt({config,prompt,sessionID:conversation.session_id,seedMessages:conversation.messages.filter(item=>!item.error).slice(-32).map(item=>({role:item.role,content:item.content})),signal:controller.signal,onSession:(sessionID)=>update(item=>({...item,session_id:sessionID})),onDelta:(content)=>update(item=>({...item,messages:item.messages.map(message=>message.id===assistant.id?{...message,content}:message)}))}); update(item=>({...item,session_id:result.sessionID||item.session_id,messages:item.messages.map(message=>message.id===assistant.id?{...message,content:result.content,created_at:now()}:message),updated_at:now()})); }
		catch(error){if(generation!==requestRef.current)return; if((error as Error).name!=='AbortError'){const message=error instanceof Error?error.message:'AI 服務目前無法使用'; update(item=>({...item,messages:item.messages.map(value=>value.id===assistant.id?{...value,content:message,error:true}:value),updated_at:now()})); setNotice(message)}else update(item=>({...item,messages:item.messages.filter(value=>value.id!==assistant.id)}));}
		finally{if(generation===requestRef.current){abortRef.current=null;setRequest('idle');setPendingID('')}} };
	const keyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();void submit()}};
	const label=runtime==='ready'?'AI 對話已就緒':runtime==='loading'?'正在讀取 AI 設定':runtime==='unconfigured'?'尚未設定 AI 模型':'AI 執行環境不可用';
	return <section className="ai-chat-workspace"><aside className="ai-thread-rail"><header><div><span>AI WORKSPACE</span><strong>對話記錄</strong></div><button type="button" onClick={createConversation} aria-label="新增對話"><MessageSquarePlus size={17}/></button></header><div className="ai-thread-list">{conversations.map(item=><button type="button" key={item.id} className={item.id===activeID?'active':''} onClick={()=>setActiveID(item.id)}><span><strong>{item.title}</strong><small>{item.messages.length?`${item.messages.length} 則訊息`:'空白對話'}</small></span><i role="button" tabIndex={0} aria-label="刪除對話" onClick={event=>{event.stopPropagation();removeConversation(item.id)}}><Trash2 size={13}/></i></button>)}</div><div className="ai-local-note"><span className={`status-dot ${runtime}`}/><div><strong>{label}</strong><small>對話僅保存在目前裝置</small></div></div></aside><div className="ai-conversation-panel"><header className="ai-conversation-header"><div className="ai-assistant-avatar"><Bot size={20}/></div><div><strong>{active?.title||'AI 研究助手'}</strong><span>{label}</span></div></header><div className={`ai-message-stage ${active?.messages.length?'has-messages':''}`}>{!active?.messages.length?<div className="ai-welcome"><div className="ai-welcome-mark"><Bot size={28}/></div><span>AI RESEARCH COPILOT</span><h2>今天想研究什麼？</h2><p>描述問題後，AI 會以目前設定的模型協助整理；請自行核對關鍵事實。</p></div>:<div className="ai-message-list">{active.messages.map(message=><article key={message.id} className={`ai-message ${message.role} ${message.error?'error':''} ${message.id===pendingID?'pending':''}`}><div className="ai-message-avatar">{message.role==='user'?<UserRound size={16}/>:<Bot size={16}/>}</div><div className="ai-message-body"><header><strong>{message.role==='user'?'你':'AI 助手'}</strong></header>{message.content&&<MessageContent content={message.content} markdown={message.role==='assistant'&&!message.error}/>} {message.id===pendingID&&<div className="ai-answering" role="status">AI 正在回答…</div>}</div></article>)}<div ref={endRef}/></div>}</div><form className="ai-composer-wrap" onSubmit={event=>void submit(event)}><div className={`ai-composer ${request==='streaming'?'sending':''}`}><textarea ref={inputRef} value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={keyDown} disabled={!config||runtime!=='ready'} placeholder={runtime==='ready'?'描述要研究的問題，Enter 傳送':'請先完成 AI 模型設定'} rows={1}/><div className="ai-composer-actions"><span>{notice||'AI 可能會犯錯，請核對關鍵事實。'}</span>{request==='streaming'?<button type="button" className="stop" onClick={stop}><Square size={14}/>停止</button>:<button type="submit" disabled={!draft.trim()||runtime!=='ready'}><Send size={15}/>傳送</button>}</div></div>{runtime!=='ready'&&<button type="button" className="ai-configure-hint" onClick={onOpenSettings}><Settings size={14}/>{runtime==='unavailable'?'查看 AI 設定':'設定 AI 模型'}</button>}</form></div></section>;
}
