import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const identity = require('../identity.cjs');
const { resolveUpdateFeed } = require('../update-feed.cjs');

// Compatibility identifier generated by electron-builder 26.15.3 for the B3
// appId. This identifies an existing NSIS installation, not the new product.
export const INSTALLER_GUID = 'eb24a227-c83c-579e-acc2-db5a4e491d81';
export const runtimeModules = ['main.cjs','app-lifecycle.cjs','identity.cjs','preload.cjs','backend-process.cjs','runtime-logger.cjs','data-protection.cjs','hermes-runtime-root.cjs','update-feed.cjs','update-manager.cjs','user-data-migration.cjs','subscription-ai-url.cjs','external-links.cjs','update-restart.cjs'];

export function desktopBuildConfig({ desktopRoot, resources, version, electronVersion, platform, arch, mode, signed = false, notarize = false }) {
  if (!['mac','windows'].includes(platform) || !['x64','arm64'].includes(arch) || !['dir','release'].includes(mode)) throw new Error('Invalid desktop build target');
  const stem = `mystocktracer-v${version}`;
  return {
    appId: identity.appId, productName: identity.name, executableName: identity.name, electronVersion,
    copyright: 'Copyright © mystocktracer contributors; portions © jundizhou (easy-stock)',
    directories: { output: path.join(desktopRoot,'dist',`builder-${mode}`), buildResources: path.join(desktopRoot,'assets') },
    files: [...runtimeModules,'package.json','assets/mystocktracer.png','!dist{,/**/*}','!resources{,/**/*}','!scripts{,/**/*}','!test{,/**/*}'],
    extraResources: [{ from: resources, to: 'resources' }, { from: path.join(desktopRoot,'state-copy.py'), to: 'state-copy.py' }],
    asar: true, publish: [resolveUpdateFeed()],
    mac: { category:'public.app-category.finance', icon:path.join(desktopRoot,'assets/mystocktracer.icns'), artifactName:`${stem}-macos-${arch}.\${ext}`, hardenedRuntime:true, gatekeeperAssess:false, identity:signed ? undefined : '-', notarize },
    dmg: { artifactName:`${stem}-macos-${arch}.dmg` },
    win: { icon:path.join(desktopRoot,'assets/mystocktracer.ico'), artifactName:`${stem}-windows-${arch}.\${ext}`, ...(signed ? {} : { signExecutable:false }) },
    nsis: { guid:INSTALLER_GUID, oneClick:true, perMachine:false, allowElevation:true, deleteAppDataOnUninstall:false, artifactName:`${stem}-windows-${arch}-setup.exe` },
  };
}
